#!/usr/bin/env python3
"""Image Gen - Image Gen 模块

@version: 5.0.0
@author: ClawsJoy
@date: 2026-5-31
"""

import sys

from lib.smart_config import smart_config

sys.path.insert(0, "str(smart_config.ROOT)")
import hashlib
import os
from datetime import datetime

from PIL import Image, ImageDraw, ImageFont


class ImageGenSkill:
    name = "image_gen"
    description = "生成图像"
    version = "1.0.0"
    category = "tools"

    def execute(self, params):
        prompt = params.get("prompt", "默认图像")
        width = params.get("width", 800)
        height = params.get("height", 600)

        os.makedirs("output", exist_ok=True)

        output_path = f"output/gen_{hashlib.md5(prompt.encode()).hexdigest()[:8]}.png"

        # 创建图像
        img = Image.new("RGB", (width, height), color=(100, 80, 160))
        draw = ImageDraw.Draw(img)

        # 绘制渐变效果
        for i in range(height):
            color = (100 + i // 3, 80 + i // 4, 160 + i // 5)
            draw.line([(0, i), (width, i)], fill=color)

        # 绘制文字
        try:
            font = ImageFont.truetype(
                "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 24
            )
        except Exception as e:
            font = ImageFont.load_default()

        # 分行显示文字
        words = prompt.split()
        lines = []
        current_line = ""
        for word in words:
            if len(current_line + word) < 30:
                current_line += word + " "
            else:
                lines.append(current_line)
                current_line = word + " "
        lines.append(current_line)

        y = height // 2 - 50
        for line in lines:
            draw.text((50, y), line, fill=(255, 255, 255), font=font)
            y += 35

        # 添加时间戳
        draw.text(
            (50, height - 30),
            f"Generated by ClawsJoy at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            fill=(200, 200, 200),
            font=font,
        )

        img.save(output_path)

        return {
            "success": True,
            "image_path": output_path,
            "prompt": prompt,
            "size": f"{width}x{height}",
            "message": f"图像已生成: {output_path}",
        }


skill = ImageGenSkill()
