last_updated: '2026-05-17T13:21:49.295995'
modules:
  active_runner:
    path: bin/active_runner.py
    registered_at: '2026-05-17T13:21:49.002808'
    status: active
    type: core
    version: v0.0.00_unknown
  memory_writer:
    path: lib/memory_writer_v1.0.01_20260517.py
    registered_at: '2026-05-17T13:21:48.922490'
    status: active
    type: core
    version: v1.0.01_20260517
  success_monitor:
    path: intelligence/success_monitor_v1.0.01_20260517.py
    registered_at: '2026-05-17T13:21:48.763139'
    status: active
    type: monitor
    version: v1.0.01_20260517
  version_manager:
    path: lib/version_manager_v1.0.01_20260517.py
    registered_at: '2026-05-17T13:21:48.843949'
    status: active
    type: core
    version: v1.0.01_20260517
  web_dashboard:
    path: web_dashboard.py
    registered_at: '2026-05-17T13:21:49.295985'
    status: active
    type: web
    version: v0.0.00_20260517_nogit
system_version: 3.0.0
