from lib.smart_config import smart_config
"""简单图像生成服务 - 使用 PIL 生成占位图"""
from PIL import Image, ImageDraw
import os
import hashlib
from datetime import datetime

class SimpleImageGen:
    @staticmethod
    def generate(prompt, output_path=None):
        """生成简单图像"""
        if output_path is None:
            output_path = f"output/generated_{hashlib.md5(prompt.encode()).hexdigest()[:8]}.png"
        
        os.makedirs("output", exist_ok=True)
        
        # 创建渐变背景
        img = Image.new('RGB', (800, 600), color=(100, 80, 160))
        draw = ImageDraw.Draw(img)
        
        # 绘制文字
        draw.text((50, 250), prompt[:50], fill=(255, 255, 255))
        draw.text((50, 300), f"Generated by ClawsJoy at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", fill=(200, 200, 200))
        
        img.save(output_path)
        return output_path

if __name__ == "__main__":
    path = SimpleImageGen.generate("测试图像")
    print(f"图像已生成: {path}")
